In [0]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive

In [0]:
# (ORIGIN, MONTH) LOOKUP TABLE
import pandas as pd

filenames = ['jan', 'feb', 'mar', 'apr', 'may', 'jun', 'jul', 'aug', 'sep', 'oct', 'nov', 'dec']

custom_df = pd.DataFrame()

for name in filenames:
  path = "/content/drive/My Drive/PROJECT 1001/Data3/new_data_" + name + ".csv"
  df = pd.read_csv(path)
  df['ORIGIN_COMBINED'] = list(zip(df.ORIGIN, df.MONTH))

  feature_df = df.query('ARR_DEL15==1').groupby('ORIGIN_COMBINED')['ARR_DEL15'].count()
  feature_df = pd.concat([feature_df, df.query('ARR_DEL15==0').groupby('ORIGIN_COMBINED')['ARR_DEL15'].count()], axis=1)
  feature_df.columns = ['DELAY_YES', 'DELAY_NO']
  feature_df['TOTAL'] = feature_df['DELAY_YES'] + feature_df['DELAY_NO']
  feature_df['DELAY_TO_NO_DELAY_RATIO'] = feature_df['DELAY_YES'] / feature_df['DELAY_NO']
  feature_df['DELAY_PROB'] = feature_df['DELAY_YES'] / feature_df['TOTAL']

  minimum = feature_df["DELAY_TO_NO_DELAY_RATIO"].min()
  q25 = feature_df["DELAY_TO_NO_DELAY_RATIO"].quantile(0.25)
  median = feature_df["DELAY_TO_NO_DELAY_RATIO"].quantile(0.5)
  q75 = feature_df["DELAY_TO_NO_DELAY_RATIO"].quantile(0.75)
  maximum = feature_df["DELAY_TO_NO_DELAY_RATIO"].max()

  feature_df['DelayScore'] = 0
  score_list = []
  for x in range(len(feature_df)):
    ratio = feature_df["DELAY_TO_NO_DELAY_RATIO"].iloc[x]
    if ratio <= minimum:
      score = 1
    elif ratio <= q25:
      score = 2
    elif ratio <= median:
      score = 3
    elif ratio <= q75:
      score = 4
    else:
      score = 5
    score_list.append(score)
  feature_df['DelayScore'] = score_list
  custom_df = custom_df.append(feature_df)

In [0]:
custom_df.head()

                 DELAY_YES  DELAY_NO  ...  DELAY_PROB  DelayScore
ORIGIN_COMBINED                       ...
(ATL, 1)              4699     24792  ...    0.159337           3
(AZA, 1)                39       390  ...    0.090909           1
(BOS, 1)              2311      7932  ...    0.225617           5
(CLT, 1)              3359     14019  ...    0.193290           4
(DCA, 1)              1963      8271  ...    0.191812           4

[5 rows x 6 columns]

In [0]:
custom_df.to_csv('origin_delay_lookup.csv')
!cp 'origin_delay_lookup.csv' 'drive/My Drive/PROJECT 1001/'

In [0]:
# (DEST, MONTH) LOOKUP TABLE

import pandas as pd

filenames = ['jan', 'feb', 'mar', 'apr', 'may', 'jun', 'jul', 'aug', 'sep', 'oct', 'nov', 'dec']

custom_df = pd.DataFrame()

for name in filenames:
  path = "/content/drive/My Drive/PROJECT 1001/Data3/new_data_" + name + ".csv"
  df = pd.read_csv(path)
  df['DEST_COMBINED'] = list(zip(df.DEST, df.MONTH))
  feature_df = df.query('ARR_DEL15==1').groupby('DEST_COMBINED')['ARR_DEL15'].count()
  feature_df = pd.concat([feature_df, df.query('ARR_DEL15==0').groupby('DEST_COMBINED')['ARR_DEL15'].count()], axis=1)
  feature_df.columns = ['DELAY_YES', 'DELAY_NO']
  feature_df['TOTAL'] = feature_df['DELAY_YES'] + feature_df['DELAY_NO']
  feature_df['DELAY_TO_NO_DELAY_RATIO'] = feature_df['DELAY_YES'] / feature_df['DELAY_NO']
  feature_df['DELAY_PROB'] = feature_df['DELAY_YES'] / feature_df['TOTAL']

  minimum = feature_df["DELAY_TO_NO_DELAY_RATIO"].min()
  q25 = feature_df["DELAY_TO_NO_DELAY_RATIO"].quantile(0.25)
  median = feature_df["DELAY_TO_NO_DELAY_RATIO"].quantile(0.5)
  q75 = feature_df["DELAY_TO_NO_DELAY_RATIO"].quantile(0.75)
  maximum = feature_df["DELAY_TO_NO_DELAY_RATIO"].max()

  feature_df['DelayScore'] = 0
  score_list = []
  for x in range(len(feature_df)):
    ratio = feature_df["DELAY_TO_NO_DELAY_RATIO"].iloc[x]
    if ratio <= minimum:
      score = 1
    elif ratio <= q25:
      score = 2
    elif ratio <= median:
      score = 3
    elif ratio <= q75:
      score = 4
    else:
      score = 5
    score_list.append(score)
  feature_df['DelayScore'] = score_list
  custom_df = custom_df.append(feature_df)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:13: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  del sys.path[0]

In [0]:
custom_df.head()

       DELAY_YES  DELAY_NO  ...  DELAY_PROB  DelayScore
ABE 1       73.0     182.0  ...    0.286275           5
ABI 1       29.0     137.0  ...    0.174699           3
ABQ 1      205.0    1244.0  ...    0.141477           2
ABR 1        4.0      56.0  ...    0.066667           2
ABY 1       10.0      68.0  ...    0.128205           2

[5 rows x 6 columns]

In [0]:
custom_df.to_csv('dest_delay_lookup.csv')
!cp 'dest_delay_lookup.csv' 'drive/My Drive/PROJECT 1001/'

In [0]:
# WEATHER LOOKUP TABLE
# Source: https://www.ncei.noaa.gov/access/search/data-search/global-summary-of-the-day
import pandas as pd
filenames = ['ORD.csv',   'CLT.csv',   'MDW.csv',   'ATL.csv',   'BOS.csv',   'DFW.csv',   'DEN.csv',   'IAH.csv',   'LAX.csv',   'LAS.csv',
             'DTW.csv',   'HOU.csv',   'DCA.csv',   'IAD.csv',   'PHX.csv',   'SAN.csv',   'SFO.csv',   'SEA.csv',   'AZA.csv',   'LGA.csv',
             'PHL.csv',   'EWR.csv',   'MSP.csv',   'JFK.csv',   'MCO.csv']
custom_df = pd.DataFrame()

for name in filenames:
  path = "/content/drive/My Drive/PROJECT 1001/Data5/" + name
  df = pd.read_csv(path)
  df['STATION'] = name.replace('.csv', '')
  df['AIRPORT_DATE'] = list(zip(df.STATION, df.DATE))
  custom_df = custom_df.append(df)

In [0]:
custom_df.head()

  STATION        DATE  LATITUDE  ...  SNDP  FRSHTT       AIRPORT_DATE
0     ORD  2018-01-01    41.995  ...   1.2       0  (ORD, 2018-01-01)
1     ORD  2018-01-02    41.995  ...   1.2       0  (ORD, 2018-01-02)
2     ORD  2018-01-03    41.995  ...   1.2    1000  (ORD, 2018-01-03)
3     ORD  2018-01-04    41.995  ...   1.2       0  (ORD, 2018-01-04)
4     ORD  2018-01-05    41.995  ...   1.2       0  (ORD, 2018-01-05)

[5 rows x 29 columns]

In [0]:
custom_df.to_csv('weather_lookup.csv')
!cp 'weather_lookup.csv' 'drive/My Drive/PROJECT 1001/'

###Tests/ Trials

In [0]:
df['ORIGIN_COMBINED'] = list(zip(df.ORIGIN_CITY_NAME, df.ORIGIN, df.MONTH))
df.head(5)

feature_df = df.query('ARR_DEL15==1').groupby('ORIGIN_COMBINED')['ARR_DEL15'].count()
feature_df = pd.concat([feature_df, df.query('ARR_DEL15==0').groupby('ORIGIN_COMBINED')['ARR_DEL15'].count()], axis=1)
feature_df.columns = ['DELAY_YES', 'DELAY_NO']
feature_df['TOTAL'] = feature_df['DELAY_YES'] + feature_df['DELAY_NO']
feature_df['DELAY_TO_NO_DELAY_RATIO'] = feature_df['DELAY_YES'] / feature_df['DELAY_NO']
feature_df['DELAY_PROB'] = feature_df['DELAY_YES'] / feature_df['TOTAL']
#feature_df

feature_df.describe()

         DELAY_YES      DELAY_NO  ...  DELAY_TO_NO_DELAY_RATIO  DELAY_PROB
count    25.000000     25.000000  ...                25.000000   25.000000
mean   2506.000000  10780.560000  ...                 0.236376    0.189190
std    1411.813019   5462.157663  ...                 0.063172    0.040734
min      92.000000    363.000000  ...                 0.113665    0.102064
25%    1663.000000   8524.000000  ...                 0.194370    0.162738
50%    2151.000000  10415.000000  ...                 0.220385    0.180587
75%    3147.000000  11948.000000  ...                 0.271466    0.213506
max    6677.000000  26475.000000  ...                 0.372895    0.271612

[8 rows x 5 columns]

In [0]:
minimum = feature_df["DELAY_TO_NO_DELAY_RATIO"].min()
q25 = feature_df["DELAY_TO_NO_DELAY_RATIO"].quantile(0.25)
median = feature_df["DELAY_TO_NO_DELAY_RATIO"].quantile(0.5)
q75 = feature_df["DELAY_TO_NO_DELAY_RATIO"].quantile(0.75)
maximum = feature_df["DELAY_TO_NO_DELAY_RATIO"].max()

feature_df['DelayScore'] = 0

In [0]:
score_list = []
for x in range(len(feature_df)):
  ratio = feature_df["DELAY_TO_NO_DELAY_RATIO"].iloc[x]
  if ratio <= minimum:
    score = 1
  elif ratio <= q25:
    score = 2
  elif ratio <= median:
    score = 3
  elif ratio <= q75:
    score = 4
  else:
    score = 5
  score_list.append(score)

feature_df['DelayScore'] = score_list
feature_df

                                  DELAY_YES  DELAY_NO  ...  DELAY_PROB  DelayScore
ORIGIN_COMBINED                                        ...
(Atlanta, GA, ATL, 12)                 4755     26475  ...    0.152257           2
(Boston, MA, BOS, 12)                  1892      9691  ...    0.163343           3
(Charlotte, NC, CLT, 12)               3451     14403  ...    0.193290           4
(Chicago, IL, MDW, 12)                 1882      5047  ...    0.271612           5
(Chicago, IL, ORD, 12)                 6677     20649  ...    0.244346           5
(Dallas/Fort Worth, TX, DFW, 12)       4632     17603  ...    0.208320           4
(Denver, CO, DEN, 12)                  3140     15616  ...    0.167413           3
(Detroit, MI, DTW, 12)                 1266     11138  ...    0.102064           1
(Houston, TX, HOU, 12)                 1180      3755  ...    0.239108           5
(Houston, TX, IAH, 12)                 3147     11419  ...    0.216051           5
(Las Vegas, NV, LAS, 12)               2151     10576  ...    0.169011           3
(Los Angeles, CA, LAX, 12)             3237     14935  ...    0.178131           3
(Minneapolis, MN, MSP, 12)             1663     10547  ...    0.136200           2
(New York, NY, JFK, 12)                1933      8771  ...    0.180587           3
(New York, NY, LGA, 12)                2686     10567  ...    0.202671           4
(Newark, NJ, EWR, 12)                  2776      8524  ...    0.245664           5
(Orlando, FL, MCO, 12)                 2621      9655  ...    0.213506           4
(Philadelphia, PA, PHL, 12)            1618      7989  ...    0.168419           3
(Phoenix, AZ, AZA, 12)                   92       363  ...    0.202198           4
(Phoenix, AZ, PHX, 12)                 2679     11948  ...    0.183154           4
(San Diego, CA, SAN, 12)               1229      6323  ...    0.162738           2
(San Francisco, CA, SFO, 12)           3598     10415  ...    0.256762           5
(Seattle, WA, SEA, 12)                 1719      8919  ...    0.161591           2
(Washington, DC, DCA, 12)              1726      9237  ...    0.157439           2
(Washington, DC, IAD, 12)               900      4949  ...    0.153872           2

[25 rows x 6 columns]